// Generated by @aponiajs/cli. Do not edit.
import { defineModule, provideClass } from "@aponiajs/common";
import { defineControllerRoutes } from "@aponiajs/platform-elysia";
import { t } from "elysia";
import { CreateUserSchema, UserSchema } from "./models/user.schema.ts";
import { UsersController } from "./users/users.controller.ts";
import { UsersService } from "./users/users.service.ts";

const UsersModuleDescriptor = defineModule({
  id: "UsersModule",
  controllers: [
    defineControllerRoutes(UsersController, {
      path: "users",
      inject: [UsersService],
      routes: [
        {
          method: "GET",
          path: "",
          propertyKey: "findAll",
          schema: {
            response: t.Array(t.Object({ id: t.Number(), name: t.String() })),
          },
        },
        {
          method: "GET",
          path: ":id",
          propertyKey: "findById",
          parameters: [{ index: 0, kind: "params", property: "id" }],
          schema: {
            params: t.Object({ id: t.Number() }),
            response: UserSchema,
          },
        },
        {
          method: "POST",
          path: "",
          propertyKey: "create",
          parameters: [{ index: 0, kind: "body", property: undefined }],
          schema: {
            body: CreateUserSchema,
            response: UserSchema,
          },
        },
      ] as const,
    }),
  ],
  providers: [provideClass(UsersService, [])],
});

export const AppModuleDescriptor = defineModule({
  id: "AppModule",
  imports: [UsersModuleDescriptor],
});

export const moduleDescriptorArtifact = Object.freeze({
  framework: "1.0.0-beta.24",
  elysia: "2.0.0-beta.24",
  modules: Object.freeze({
    AppModule: AppModuleDescriptor,
    UsersModule: UsersModuleDescriptor,
  }),
});
