/**
 * The closed union of failure codes every framework boundary throws with.
 *
 * Tests assert on the code, never on message text; a new failure mode extends
 * this union rather than throwing a bare `Error`.
 */
export type AponiaErrorCode =
  | "MODULE_CYCLE"
  | "DUPLICATE_MODULE"
  | "DUPLICATE_PROVIDER"
  | "DUPLICATE_ROUTE"
  | "INVALID_EXPORT"
  | "AMBIGUOUS_PROVIDER"
  | "MISSING_PROVIDER"
  | "PROVIDER_CYCLE"
  | "INVALID_PROVIDER"
  | "UNSUPPORTED_PROVIDER_SCOPE"
  | "MISSING_REQUEST_CONTEXT"
  | "INVALID_SCOPE_HIERARCHY"
  | "UNRESOLVED_CONSTRUCTOR_DEPENDENCIES"
  | "INVALID_CONFIGURATION"
  | "INVALID_CONFIGURATION_VALUE"
  | "INVALID_CONTROLLER"
  | "INVALID_MODULE"
  | "INVALID_PIPE"
  | "INVALID_PIPE_VALUE"
  | "INVALID_MIDDLEWARE"
  | "INVALID_VALIDATION_MODEL"
  | "INVALID_NATIVE_APPLICATION"
  | "UNSUPPORTED_ELYSIA_VERSION"
  | "APPLICATION_NOT_LISTENING"
  | "UNSUPPORTED_CONTROLLER"
  | "INVALID_WEBSOCKET_GATEWAY"
  | "DUPLICATE_WEBSOCKET_GATEWAY"
  | "DUPLICATE_WEBSOCKET_HANDLER"
  | "INVALID_WEBSOCKET_MESSAGE"
  | "UNKNOWN_WEBSOCKET_EVENT"
  | "WEBSOCKET_HANDLER_ERROR";
