export type AponiaErrorCode =
  | "MODULE_CYCLE"
  | "DUPLICATE_MODULE"
  | "DUPLICATE_PROVIDER"
  | "INVALID_EXPORT"
  | "AMBIGUOUS_PROVIDER"
  | "MISSING_PROVIDER"
  | "PROVIDER_CYCLE"
  | "INVALID_CONTROLLER"
  | "INVALID_MODULE"
  | "INVALID_NATIVE_APPLICATION"
  | "APPLICATION_NOT_LISTENING"
  | "UNSUPPORTED_CONTROLLER";
