import { describe, expect, test } from "bun:test";
import { join } from "node:path";
import {
  analyzeControllerRoutes,
  analyzeModuleDescriptors,
  collectSourceImports,
  descriptorModuleFileName,
  emitModuleDescriptors,
} from "../src/index.ts";
import type {
  DescriptorSourceFile,
  EmittedModuleDescriptors,
  ModuleDescriptorProvenance,
} from "../src/index.ts";

/**
 * The emitted descriptor module is the build's public artifact, so these cases
 * assert its text and its decline report together: what a build can state, and
 * what it says instead when it cannot.
 */

/** Every fixture shares one project layout, so a relative import stays readable in the expectations. */
const projectRoot = "/project/src";
const generatedFile = join(projectRoot, descriptorModuleFileName);

/**
 * Every fixture shares one provenance, which is the whole of what the platform
 * compares before it accepts the artifact: the release that generated it and the
 * Elysia it was generated against.
 */
const provenance: ModuleDescriptorProvenance = Object.freeze({
  framework: "9.9.9",
  elysia: "1.4.30",
});

/** The artifact trailer every generated module ends with, so a text assertion can stop at the modules. */
const artifactTrailer = `
/**
 * What the platform consumes. An artifact from another AponiaJS release, and
 * one that holds no declaration for the root module the application names,
 * are refused whole: bootstrap lowers that module from its decorators instead,
 * which costs the lowering rather than a boot that cannot start. A file from
 * this release is adopted whole, so \`aponia build\` has to run again after the
 * module graph changes.
 *
 * \`elysia\` is the version this file was generated against, or \`null\` when
 * \`aponia build\` could not resolve an installed one. It is reported with the
 * refusal so a mismatch names both sides.
 */
export const moduleDescriptorArtifact = Object.freeze({
  framework: "9.9.9",
  elysia: "1.4.30",
  modules: Object.freeze({
`;

function sourceFile(name: string, source: string): DescriptorSourceFile {
  const path = join(projectRoot, name);
  return {
    file: path,
    imports: collectSourceImports(source, path),
    descriptors: analyzeModuleDescriptors(source, path),
    controllers: analyzeControllerRoutes(source, path),
  };
}

function emit(sources: Readonly<Record<string, string>>): EmittedModuleDescriptors {
  return emitModuleDescriptors(
    Object.entries(sources).map(([name, source]) => sourceFile(name, source)),
    generatedFile,
    provenance,
  );
}

const serviceSource = `import { Injectable } from "@aponiajs/common";

@Injectable()
export class AuditService {}
`;

const moduleSource = `import { Module } from "@aponiajs/common";
import { AuditService } from "./audit.service.ts";

@Module({ providers: [AuditService], exports: [AuditService] })
export class AuditModule {}
`;

describe("emitModuleDescriptors", () => {
  test("writes a module's graph as literal descriptor source", () => {
    const emitted = emit({ "audit.service.ts": serviceSource, "audit.module.ts": moduleSource });

    // The artifact is what an application hands the platform, so the file
    // states its provenance beside the module it declared: the platform refuses
    // it whole when the release that generated it is not the one running, and
    // the descriptor key is the root module name a boot looks up.
    expect(emitted.source).toBe(`// Generated by @aponiajs/cli. Do not edit.
import { defineModule, provideClass } from "@aponiajs/common";
import { AuditService } from "./audit.service.ts";

const AuditModuleDescriptor = defineModule({
  id: "AuditModule",
  providers: [
    provideClass(AuditService, []),
  ],
  exports: [
    AuditService,
  ],
});
${artifactTrailer}    AuditModule: AuditModuleDescriptor,
  }),
});
`);
    expect(emitted.declined).toEqual([]);
  });

  test("records the provenance the platform compares before it accepts the artifact", () => {
    const emitted = emitModuleDescriptors(
      [sourceFile("audit.module.ts", moduleSource), sourceFile("audit.service.ts", serviceSource)],
      generatedFile,
      { framework: "0.0.0", elysia: null },
    );

    // An unresolved Elysia is written as `null` rather than left out: the
    // platform reports what the artifact recorded when it refuses one, so the
    // file has to say that the build could not resolve an installed Elysia.
    expect(emitted.source).toContain('  framework: "0.0.0",');
    expect(emitted.source).toContain("  elysia: null,");
  });

  test("declares a controller's routes, its inject list, and every schema slot", () => {
    const emitted = emit({
      "users.service.ts": `import { Injectable } from "@aponiajs/common";

@Injectable()
export class UsersService {}
`,
      "users.controller.ts": `import { Body, Controller, Get, Param, Post, Query } from "@aponiajs/common";
import { CreateUser, UserParams } from "./users.model.ts";
import { UsersService } from "./users.service.ts";

@Controller("users")
export class UsersController {
  constructor(private readonly usersService: UsersService) {}

  @Get(":id")
  read(@Param() params: UserParams): string {
    return "read";
  }

  @Post("/", { body: CreateUser, response: { 201: CreateUser } })
  create(@Body() body: CreateUser): string {
    return "created";
  }

  @Get()
  async list(@Query("page") page: string): Promise<string> {
    return "list";
  }
}
`,
      "users.model.ts": `import { Validation } from "@aponiajs/common";
import { t } from "elysia";

@Validation(t.Object({ name: t.String() }))
export class CreateUser {}

@Validation(t.Object({ id: t.String() }))
export class UserParams {}
`,
      "users.module.ts": `import { Module } from "@aponiajs/common";
import { UsersController } from "./users.controller.ts";
import { UsersService } from "./users.service.ts";

@Module({
  controllers: [UsersController],
  providers: [UsersService],
  exports: [UsersService],
})
export class UsersModule {}
`,
    });

    expect(emitted.declined).toEqual([]);
    const source = emitted.source ?? "";

    // `defineControllerRoutes` is the platform's own descriptor authoring
    // surface, so the file imports the two packages the helper names live in.
    expect(source).toContain('import { defineModule, provideClass } from "@aponiajs/common";');
    expect(source).toContain('import { defineControllerRoutes } from "@aponiajs/platform-elysia";');
    expect(source).toContain('import { t } from "elysia";');
    expect(source).toContain(
      [
        "    defineControllerRoutes(UsersController, {",
        '      path: "users",',
        "      inject: [UsersService],",
        "      routes: [",
        "        {",
        '          method: "GET",',
        '          path: ":id",',
        '          propertyKey: "read",',
        "          parameters: [",
        // `property` is written even when no decorator named one: the platform's
        // metadata requires the field, and a generated module is source in the
        // application's own type check.
        '            { index: 0, kind: "params", property: undefined },',
        "          ],",
        "          promiseCapable: false,",
        "        },",
      ].join("\n"),
    );
    // A model class is resolved to the validator it declares, and a status-keyed
    // response map keeps the literal that declares it.
    expect(source).toContain(
      "schema: { body: t.Object({ name: t.String() }), response: { 201: t.Object({ name: t.String() }) } },",
    );
    // A decorated parameter is declared; an async handler keeps the
    // Promise-capable default rather than claiming to be synchronous.
    expect(source).toContain('{ index: 0, kind: "query", property: "page" },');
    expect(source).toContain(
      ['          method: "GET",', '          path: "",', '          propertyKey: "list",'].join(
        "\n",
      ),
    );
  });

  test("declares the whole context for a handler that declares a parameter and binds none", () => {
    const emitted = emit({
      "plain.controller.ts": `import { Controller, Get } from "@aponiajs/common";

@Controller("plain")
export class PlainController {
  @Get()
  read(first: string) {
    return first;
  }
}
`,
      "plain.module.ts": `import { Module } from "@aponiajs/common";
import { PlainController } from "./plain.controller.ts";

@Module({ controllers: [PlainController] })
export class PlainModule {}
`,
    });

    expect(emitted.source).toContain("takesContext: true,");
    expect(emitted.declined).toEqual([]);
  });

  test("copies a module's own provider expressions verbatim and imports the names they read", () => {
    const emitted = emit({
      "tokens.ts": `import { createToken, provideValue } from "@aponiajs/common";

export const ANSWER = createToken<number>("ANSWER");
export const answerProvider = provideValue(ANSWER, 42);
`,
      "answer.module.ts": `import { Module } from "@aponiajs/common";
import { answerProvider } from "./tokens.ts";

@Module({ providers: [answerProvider] })
export class AnswerModule {}
`,
    });

    expect(emitted.declined).toEqual([]);
    expect(emitted.source).toContain('import { answerProvider } from "./tokens.ts";');
    expect(emitted.source).toContain("providers: [");
    expect(emitted.source).toContain("    answerProvider,");
  });

  test("states an injected token by name and a declared type as the design type", () => {
    const emitted = emit({
      "tokens.ts": `import { createToken } from "@aponiajs/common";

export const API_KEY = createToken<string>("API_KEY");
`,
      "users.service.ts": `import { Inject, Injectable } from "@aponiajs/common";
import { API_KEY } from "./tokens.ts";
import { AuditService } from "./audit.service.ts";

@Injectable()
export class UsersService {
  constructor(
    @Inject(API_KEY) private readonly apiKey: string,
    private readonly audit: AuditService,
  ) {}
}
`,
      "audit.service.ts": `import { Injectable } from "@aponiajs/common";

@Injectable()
export class AuditService {}
`,
      "users.module.ts": `import { Module } from "@aponiajs/common";
import { UsersService } from "./users.service.ts";

@Module({ providers: [UsersService] })
export class UsersModule {}
`,
    });

    expect(emitted.declined).toEqual([]);
    expect(emitted.source).toContain("provideClass(UsersService, [API_KEY, AuditService]),");
    expect(emitted.source).toContain('import { API_KEY } from "./tokens.ts";');
  });

  test("imports a validator from the bare specifier the application imported it from", () => {
    const emitted = emit({
      "items.controller.ts": `import { Body, Controller, Post } from "@aponiajs/common";
import { t } from "elysia";

@Controller("items")
export class ItemsController {
  @Post("/", { body: t.Object({ name: t.String() }) })
  create(@Body() body: { name: string }): void {}
}
`,
      "items.module.ts": `import { Module } from "@aponiajs/common";
import { ItemsController } from "./items.controller.ts";

@Module({ controllers: [ItemsController] })
export class ItemsModule {}
`,
    });

    expect(emitted.declined).toEqual([]);
    expect(emitted.source).toContain('import { t } from "elysia";');
    expect(emitted.source).toContain("schema: { body: t.Object({ name: t.String() }) },");
  });

  test("orders the modules so a descriptor constant is declared before the module importing it", () => {
    const emitted = emit({
      "audit.module.ts": moduleSource,
      "audit.service.ts": serviceSource,
      "users.module.ts": `import { Module } from "@aponiajs/common";
import { AuditModule } from "./audit.module.ts";
import { AuditService } from "./audit.service.ts";

@Module({ imports: [AuditModule], providers: [AuditService] })
export class UsersModule {}
`,
    });

    expect(emitted.declined).toEqual([]);
    expect(emitted.source).toContain("imports: [");
    expect(emitted.source).toContain("    AuditModuleDescriptor,");
    const source = emitted.source ?? "";
    expect(source.indexOf("const AuditModuleDescriptor")).toBeLessThan(
      source.indexOf("const UsersModuleDescriptor"),
    );
    // The referenced class is never imported: a generated module names the
    // descriptor of the module it imports, not the class it was lowered from.
    expect(source).not.toContain('import { AuditModule } from "./audit.module.ts";');
  });

  test("writes no module for a project that declares none", () => {
    const emitted = emit({
      "plain.controller.ts": `import { Controller, Get } from "@aponiajs/common";

@Controller("plain")
export class PlainController {
  @Get()
  read() {}
}
`,
    });

    expect(emitted.source).toBeUndefined();
    expect(emitted.declined).toEqual([]);
  });

  test("declines a route whose schema cannot be reproduced, and the module declaring it", () => {
    const emitted = emit({
      "users.controller.ts": `import { Body, Controller, Post } from "@aponiajs/common";

@Controller("users")
export class UsersController {
  @Post("/", { body: CreateUser })
  create(@Body() body: CreateUser): void {}
}
`,
      "users.module.ts": `import { Module } from "@aponiajs/common";
import { UsersController } from "./users.controller.ts";

@Module({ controllers: [UsersController] })
export class UsersModule {}
`,
    });

    // `CreateUser` is never imported by the controller's own file, so no
    // generated module can name the validator the route declares.
    expect(emitted.source).toBeUndefined();
    expect(emitted.declined).toEqual([
      {
        kind: "route",
        module: "UsersModule",
        controller: "UsersController",
        method: "create",
        reason:
          '@Post in /project/src/users.controller.ts\'s "body" schema reads "CreateUser", which is not an import or an export of the file it was written in, so a generated module cannot name it.',
      },
      {
        kind: "module",
        module: "UsersModule",
        reason:
          '@Post in /project/src/users.controller.ts\'s "body" schema reads "CreateUser", which is not an import or an export of the file it was written in, so a generated module cannot name it.',
      },
    ]);
  });

  test("declines a schema that spreads slots the analysis cannot read", () => {
    const emitted = emit({
      "users.controller.ts": `import { Body, Controller, Post } from "@aponiajs/common";
import { shared } from "./shared.ts";

@Controller("users")
export class UsersController {
  @Post("/", { ...shared })
  create(@Body() body: unknown): void {}
}
`,
      "shared.ts": `export const shared = {};
`,
      "users.module.ts": `import { Module } from "@aponiajs/common";
import { UsersController } from "./users.controller.ts";

@Module({ controllers: [UsersController] })
export class UsersModule {}
`,
    });

    expect(emitted.declined[0]?.kind).toBe("route");
    expect(emitted.declined[0]?.reason).toContain("spreads its schema");
  });

  test("declines a route whose property key is not a plain name", () => {
    const emitted = emit({
      "users.controller.ts": `import { Controller, Get } from "@aponiajs/common";

const key = "read";

@Controller("users")
export class UsersController {
  @Get()
  [key]() {}
}
`,
      "users.module.ts": `import { Module } from "@aponiajs/common";
import { UsersController } from "./users.controller.ts";

@Module({ controllers: [UsersController] })
export class UsersModule {}
`,
    });

    expect(emitted.declined[0]?.kind).toBe("route");
    expect(emitted.declined[0]?.reason).toContain("not a plain property key");
  });

  test("declines a controller injecting a token whose identity only exists at run time", () => {
    const emitted = emit({
      "users.controller.ts": `import { Body, Controller, Inject, Post, createToken } from "@aponiajs/common";

@Controller("users")
export class UsersController {
  constructor(@Inject(createToken<string>("API_KEY")) private readonly apiKey: string) {}

  @Post("/")
  create(@Body() body: unknown): void {}
}
`,
      "users.module.ts": `import { Module } from "@aponiajs/common";
import { UsersController } from "./users.controller.ts";

@Module({ controllers: [UsersController] })
export class UsersModule {}
`,
    });

    expect(emitted.source).toBeUndefined();
    expect(emitted.declined).toEqual([
      {
        kind: "module",
        module: "UsersModule",
        reason:
          'The controller UsersController in /project/src/users.controller.ts injects createToken<string>("API_KEY"), whose identity a generated module cannot reproduce; bind the token to a named constant and inject that.',
      },
    ]);
  });

  test("declines a module whose collection entry is not a single identifier", () => {
    const emitted = emit({
      "users.module.ts": `import { Module } from "@aponiajs/common";
import { helpers } from "./helpers.ts";

@Module({ controllers: [helpers.UsersController] })
export class UsersModule {}
`,
      "helpers.ts": `import { UsersController } from "./users.controller.ts";

export const helpers = { UsersController };
`,
      "users.controller.ts": `import { Controller, Get } from "@aponiajs/common";

@Controller("users")
export class UsersController {
  @Get()
  read() {}
}
`,
    });

    expect(emitted.source).toBeUndefined();
    expect(emitted.declined).toEqual([
      {
        kind: "module",
        module: "UsersModule",
        reason:
          'The "controllers" entry "helpers.UsersController" in /project/src/users.module.ts must name its declaration with a single identifier to be lowered into a generated module.',
      },
    ]);
  });

  test("declines a module whose imports entry names a module the project does not declare", () => {
    const emitted = emit({
      "users.module.ts": `import { Module } from "@aponiajs/common";
import { AuditModule } from "@audit/audit.module.ts";

@Module({ imports: [AuditModule] })
export class UsersModule {}
`,
    });

    expect(emitted.declined[0]?.kind).toBe("module");
    expect(emitted.declined[0]?.reason).toContain(
      'no declaration named "AuditModule" was read from the project\'s own source',
    );
  });

  test("declines a module that imports a module this build did not lower", () => {
    const emitted = emit({
      "audit.module.ts": `import { Module } from "@aponiajs/common";
import { auditProviders } from "./audit.providers.ts";

@Module({ providers: [...auditProviders()] })
export class AuditModule {}
`,
      "audit.providers.ts": `import { Injectable, provideClass } from "@aponiajs/common";

@Injectable()
export class AuditService {}

export const auditProviders = () => [provideClass(AuditService, [])];
`,
      "users.module.ts": `import { Module } from "@aponiajs/common";
import { AuditModule } from "./audit.module.ts";

@Module({ imports: [AuditModule] })
export class UsersModule {}
`,
    });

    expect(emitted.source).toBeUndefined();
    expect(emitted.declined).toContainEqual({
      kind: "module",
      module: "UsersModule",
      reason: 'it imports "AuditModule", which this build did not lower into the generated module',
    });
  });

  test("declines every module of an import cycle, which has no declaration order in one file", () => {
    const emitted = emit({
      "audit.module.ts": `import { Module } from "@aponiajs/common";
import { UsersModule } from "./users.module.ts";

@Module({ imports: [UsersModule] })
export class AuditModule {}
`,
      "users.module.ts": `import { Module } from "@aponiajs/common";
import { AuditModule } from "./audit.module.ts";

@Module({ imports: [AuditModule] })
export class UsersModule {}
`,
    });

    expect(emitted.source).toBeUndefined();
    expect(emitted.declined).toContainEqual({
      kind: "module",
      module: "AuditModule",
      reason:
        "it takes part in a module import cycle, which has no declaration order in one generated file",
    });
    expect(emitted.declined).toContainEqual({
      kind: "module",
      module: "UsersModule",
      reason:
        "it takes part in a module import cycle, which has no declaration order in one generated file",
    });
  });

  test("declines a module needing a name the generated file binds for itself", () => {
    const emitted = emit({
      "define.controller.ts": `import { Controller, Get } from "@aponiajs/common";

@Controller("define")
export class defineModule {
  @Get()
  read() {}
}
`,
      "users.module.ts": `import { Module } from "@aponiajs/common";
import { defineModule } from "./define.controller.ts";

@Module({ controllers: [defineModule] })
export class UsersModule {}
`,
    });

    expect(emitted.source).toBeUndefined();
    expect(emitted.declined).toContainEqual({
      kind: "module",
      module: "UsersModule",
      reason:
        'it needs the name "defineModule", which the generated file either binds for itself or binds to two different declarations',
    });
  });

  test("declines a module whose provider entry names a class two files both declare", () => {
    const emitted = emit({
      "users.service.ts": `import { Injectable } from "@aponiajs/common";

@Injectable()
export class UsersService {}
`,
      "admin/users.service.ts": `import { Injectable } from "@aponiajs/common";

@Injectable()
export class UsersService {}
`,
      "users.module.ts": `import { Module } from "@aponiajs/common";
import { UsersService } from "./users.service.ts";

@Module({ providers: [UsersService] })
export class UsersModule {}
`,
      "admin/admin.module.ts": `import { Module } from "@aponiajs/common";
import { UsersService } from "./users.service.ts";

@Module({ providers: [UsersService] })
export class AdminModule {}
`,
    });

    // Each module is copied from its own file's import, so the two entries name
    // the same local name but two different declarations — a conflict one
    // generated file cannot resolve, which is why both modules are dropped
    // rather than one silently outranking the other.
    expect(emitted.source).toBeUndefined();
    expect(emitted.declined).toEqual([
      {
        kind: "module",
        module: "UsersModule",
        reason:
          'it needs the name "UsersService", which the generated file either binds for itself or binds to two different declarations',
      },
      {
        kind: "module",
        module: "AdminModule",
        reason:
          'it needs the name "UsersService", which the generated file either binds for itself or binds to two different declarations',
      },
    ]);
  });

  test("declines a module whose controller entry names a class two files both declare", () => {
    const emitted = emit({
      "users.controller.ts": `import { Controller, Get } from "@aponiajs/common";

@Controller("users")
export class UsersController {
  @Get()
  read() {}
}
`,
      "admin/users.controller.ts": `import { Controller, Get } from "@aponiajs/common";

@Controller("admin")
export class UsersController {
  @Get()
  read() {}
}
`,
      "users.module.ts": `import { Module } from "@aponiajs/common";
import { UsersController } from "./users.controller.ts";

@Module({ controllers: [UsersController] })
export class UsersModule {}
`,
    });

    expect(emitted.source).toBeUndefined();
    expect(emitted.declined).toEqual([
      {
        kind: "module",
        module: "UsersModule",
        reason:
          'The "controllers" entry "UsersController" in /project/src/users.module.ts cannot be lowered: two classes in the project are named "UsersController", and a generated module addresses each by that name.',
      },
    ]);
  });

  test("declines two modules that share one declared name", () => {
    const emitted = emit({
      "first/users.module.ts": `import { Module } from "@aponiajs/common";

@Module({})
export class UsersModule {}
`,
      "second/users.module.ts": `import { Module } from "@aponiajs/common";

@Module({})
export class UsersModule {}
`,
    });

    // Two classes with one name would both be declared as the same constant in
    // one file, so neither is emitted rather than one silently winning.
    expect(emitted.source).toBeUndefined();
    expect(emitted.declined).toEqual([
      {
        kind: "module",
        module: "UsersModule",
        reason:
          'two classes in the project are named "UsersModule", and a generated module addresses each module by that name',
      },
      {
        kind: "module",
        module: "UsersModule",
        reason:
          'two classes in the project are named "UsersModule", and a generated module addresses each module by that name',
      },
    ]);
  });

  test("declines an anonymous module class, which a generated module cannot key", () => {
    const emitted = emit({
      "users.module.ts": `import { Module } from "@aponiajs/common";

@Module({})
export default class {}
`,
    });

    expect(emitted.source).toBeUndefined();
    expect(emitted.declined).toEqual([
      {
        kind: "module",
        module: "",
        reason: "the module class is anonymous, so a generated module cannot key it",
      },
    ]);
  });

  test("declines a module whose collection the analysis reported as unreadable", () => {
    const emitted = emit({
      "users.module.ts": `import { Module } from "@aponiajs/common";

@Module({ controllers: controllers })
export class UsersModule {}
`,
    });

    expect(emitted.source).toBeUndefined();
    expect(emitted.declined[0]?.kind).toBe("module");
    expect(emitted.declined[0]?.reason).toContain("controllers");
  });

  test("declines a module exporting a name the file does not import as a value", () => {
    const emitted = emit({
      "users.service.ts": `import { Injectable } from "@aponiajs/common";

@Injectable()
export class UsersService {}
`,
      "users.module.ts": `import { Module } from "@aponiajs/common";
import type { UsersService } from "./users.service.ts";

@Module({ exports: [UsersService] })
export class UsersModule {}
`,
    });

    expect(emitted.source).toBeUndefined();
    expect(emitted.declined).toEqual([
      {
        kind: "module",
        module: "UsersModule",
        reason:
          'The "exports" entry "UsersService" in /project/src/users.module.ts reads "UsersService" as a value, but the file imports it as a type.',
      },
    ]);
  });

  test("declines a controller whose declared dependency the analysis could not reduce to a token", () => {
    const emitted = emit({
      "users.controller.ts": `import { Controller, Get, Injectable } from "@aponiajs/common";
import { BaseController } from "./base.controller.ts";

@Injectable()
@Controller("users")
export class UsersController extends BaseController {
  @Get()
  read() {}
}
`,
      "base.controller.ts": `export class BaseController {
  constructor(private readonly name: string) {}
}
`,
      "users.module.ts": `import { Module } from "@aponiajs/common";
import { UsersController } from "./users.controller.ts";

@Module({ controllers: [UsersController] })
export class UsersModule {}
`,
    });

    expect(emitted.source).toBeUndefined();
    expect(emitted.declined[0]?.kind).toBe("module");
    expect(emitted.declined[0]?.reason).toContain("UsersController");
  });

  test("declines a collection entry the module's own file cannot name", () => {
    // The analysis resolves a name against everything the file binds, but a
    // generated module can only import a name the file imports or exports. An
    // entry naming a declaration the file keeps to itself is declined rather
    // than written into a module that cannot see it.
    const imported = emit({
      "users.module.ts": `import { Module } from "@aponiajs/common";

@Module({ imports: [AuditModule] })
export class UsersModule {}

class AuditModule {}
`,
    });

    expect(imported.source).toBeUndefined();
    expect(imported.declined).toEqual([
      {
        kind: "module",
        module: "UsersModule",
        reason:
          'The "imports" entry "AuditModule" in /project/src/users.module.ts names "AuditModule", ' +
          "which is not an import or an export of the file it was written in.",
      },
    ]);

    const controlled = emit({
      "users.module.ts": `import { Module } from "@aponiajs/common";

@Module({ controllers: [UsersController] })
export class UsersModule {}

class UsersController {}
`,
    });

    expect(controlled.source).toBeUndefined();
    expect(controlled.declined[0]?.reason).toBe(
      'The "controllers" entry "UsersController" in /project/src/users.module.ts names "UsersController", ' +
        "which is not an import or an export of the file it was written in.",
    );
  });

  test("declines a provider whose own file does not export it as a value", () => {
    const emitted = emit({
      "users.module.ts": `import { Injectable, Module } from "@aponiajs/common";

@Injectable()
class UsersService {}

@Module({ providers: [UsersService] })
export class UsersModule {}
`,
    });

    expect(emitted.source).toBeUndefined();
    expect(emitted.declined).toEqual([
      {
        kind: "module",
        module: "UsersModule",
        reason:
          'The "providers" entry "UsersService" in /project/src/users.module.ts names "UsersService", ' +
          "which its own file does not export as a value.",
      },
    ]);
  });

  test("declines a provider whose constructor dependencies cannot be wired", () => {
    const emitted = emit({
      "base.service.ts": `export class BaseService {
  constructor(private readonly name: string) {}
}
`,
      "users.service.ts": `import { Injectable } from "@aponiajs/common";
import { BaseService } from "./base.service.ts";

@Injectable()
export class UsersService extends BaseService {}
`,
      "users.module.ts": `import { Module } from "@aponiajs/common";
import { UsersService } from "./users.service.ts";

@Module({ providers: [UsersService] })
export class UsersModule {}
`,
    });

    expect(emitted.source).toBeUndefined();
    expect(emitted.declined[0]?.kind).toBe("module");
    expect(emitted.declined[0]?.reason).toContain("UsersService");
  });

  test("declines a copied provider expression that reads a name its file cannot name", () => {
    const emitted = emit({
      "users.module.ts": `import { Module, provideValue } from "@aponiajs/common";

const localProvider = provideValue("ANSWER", 42);

@Module({ providers: [localProvider] })
export class UsersModule {}
`,
    });

    expect(emitted.source).toBeUndefined();
    expect(emitted.declined).toEqual([
      {
        kind: "module",
        module: "UsersModule",
        reason:
          'The "providers" entry "localProvider" in /project/src/users.module.ts reads "localProvider", ' +
          "which is not an import or an export of the file it was written in, so a generated module cannot name it.",
      },
    ]);
  });

  test("declines a route whose schema slot reads a name the controller's file cannot name", () => {
    const emitted = emit({
      "users.controller.ts": `import { Body, Controller, Post } from "@aponiajs/common";

const body = {};

@Controller("users")
export class UsersController {
  @Post("/", { body: body })
  create(@Body() input: unknown): void {}
}
`,
      "users.module.ts": `import { Module } from "@aponiajs/common";
import { UsersController } from "./users.controller.ts";

@Module({ controllers: [UsersController] })
export class UsersModule {}
`,
    });

    expect(emitted.source).toBeUndefined();
    expect(emitted.declined).toEqual([
      {
        kind: "route",
        module: "UsersModule",
        controller: "UsersController",
        method: "create",
        reason:
          '@Post in /project/src/users.controller.ts\'s "body" schema reads "body", which is not an import ' +
          "or an export of the file it was written in, so a generated module cannot name it.",
      },
      {
        kind: "module",
        module: "UsersModule",
        reason:
          '@Post in /project/src/users.controller.ts\'s "body" schema reads "body", which is not an import ' +
          "or an export of the file it was written in, so a generated module cannot name it.",
      },
    ]);
  });

  test("declines a controller injecting a token its own file cannot name", () => {
    const emitted = emit({
      "users.controller.ts": `import { Controller, Get, Inject, Injectable } from "@aponiajs/common";

const token = "users";

@Injectable()
@Controller("users")
export class UsersController {
  constructor(@Inject(token) private readonly name: string) {}

  @Get()
  read(): string {
    return this.name;
  }
}
`,
      "users.module.ts": `import { Module } from "@aponiajs/common";
import { UsersController } from "./users.controller.ts";

@Module({ controllers: [UsersController] })
export class UsersModule {}
`,
    });

    expect(emitted.source).toBeUndefined();
    expect(emitted.declined[0]?.kind).toBe("module");
    expect(emitted.declined[0]?.reason).toContain("UsersController");
  });

  test("declines a controller whose declared parameter type is imported as a type only", () => {
    const emitted = emit({
      "audit.service.ts": `import { Injectable } from "@aponiajs/common";

@Injectable()
export class AuditService {}
`,
      "users.controller.ts": `import { Controller, Get, Injectable } from "@aponiajs/common";
import type { AuditService } from "./audit.service.ts";

@Injectable()
@Controller("users")
export class UsersController {
  constructor(private readonly audit: AuditService) {}

  @Get()
  read(): string {
    return "read";
  }
}
`,
      "users.module.ts": `import { Module } from "@aponiajs/common";
import { UsersController } from "./users.controller.ts";

@Module({ controllers: [UsersController] })
export class UsersModule {}
`,
    });

    expect(emitted.source).toBeUndefined();
    expect(emitted.declined[0]?.kind).toBe("module");
    expect(emitted.declined[0]?.reason).toContain("UsersController");
  });

  test("imports a namespace and a default binding in the form the application wrote them", () => {
    const emitted = emit({
      "shared.ts": `export const answer = 1;
`,
      "answer.provider.ts": `import { provideValue } from "@aponiajs/common";
import { answer } from "./shared.ts";

export default provideValue("ANSWER", answer);
`,
      "answer.module.ts": `import { Module } from "@aponiajs/common";
import AnswerProvider from "./answer.provider.ts";
import * as shared from "./shared.ts";

@Module({ providers: [AnswerProvider, shared.answer] })
export class AnswerModule {}
`,
    });

    expect(emitted.declined).toEqual([]);
    expect(emitted.source).toContain('import AnswerProvider from "./answer.provider.ts";');
    expect(emitted.source).toContain('import * as shared from "./shared.ts";');
  });

  test("leaves an anonymous injectable out of the generated module, which cannot address it", () => {
    const emitted = emit({
      "audit.service.ts": `import { Injectable } from "@aponiajs/common";

@Injectable()
export class AuditService {}
`,
      "anonymous.service.ts": `import { Injectable } from "@aponiajs/common";

@Injectable()
export default class {}
`,
      "audit.module.ts": `import { Module } from "@aponiajs/common";
import { AuditService } from "./audit.service.ts";

@Module({ providers: [AuditService] })
export class AuditModule {}
`,
    });

    expect(emitted.declined).toEqual([]);
    expect(emitted.source).toContain("provideClass(AuditService, []),");
    expect(emitted.source).not.toContain("anonymous.service.ts");
  });

  test("declines every module of a chain reaching a module this build did not lower", () => {
    const emitted = emit({
      "audit.module.ts": `import { Module } from "@aponiajs/common";
import { auditProviders } from "./audit.providers.ts";

@Module({ providers: [...auditProviders()] })
export class AuditModule {}
`,
      "audit.providers.ts": `export const auditProviders = () => [];
`,
      "billing.module.ts": `import { Module } from "@aponiajs/common";
import { AuditModule } from "./audit.module.ts";

@Module({ imports: [AuditModule] })
export class BillingModule {}
`,
      "users.module.ts": `import { Module } from "@aponiajs/common";
import { BillingModule } from "./billing.module.ts";

@Module({ imports: [BillingModule] })
export class UsersModule {}
`,
    });

    expect(emitted.source).toBeUndefined();
    expect(emitted.declined).toContainEqual({
      kind: "module",
      module: "BillingModule",
      reason: 'it imports "AuditModule", which this build did not lower into the generated module',
    });
    expect(emitted.declined).toContainEqual({
      kind: "module",
      module: "UsersModule",
      reason:
        'it imports "BillingModule", which this build did not lower into the generated module',
    });
  });

  test("resolves a @Validation() model to the validator it declares", () => {
    const emitted = emit({
      "users.model.ts": `import { Validation } from "@aponiajs/common";
import { t } from "elysia";

const createUserSchema = t.Object({ name: t.String({ minLength: 2 }) });

@Validation(createUserSchema)
export class CreateUser {}
`,
      "users.controller.ts": `import { Body, Controller, Post } from "@aponiajs/common";
import { CreateUser } from "./users.model.ts";

@Controller("users")
export class UsersController {
  @Post("/", { body: CreateUser })
  create(@Body() body: CreateUser): string {
    return body.name;
  }
}
`,
      "users.module.ts": `import { Module } from "@aponiajs/common";
import { UsersController } from "./users.controller.ts";

@Module({ controllers: [UsersController] })
export class UsersModule {}
`,
    });

    expect(emitted.declined).toEqual([]);
    // The validator is stated, and the model's own private constant is folded
    // into it because a generated module cannot name what the file does not
    // export. Nothing names the class the runtime would have resolved instead.
    expect(emitted.source).toContain(
      "schema: { body: t.Object({ name: t.String({ minLength: 2 }) }) },",
    );
    expect(emitted.source).not.toContain("CreateUser");
  });

  test("folds a model constant built from another constant, and keeps a model the catalog cannot place", () => {
    const emitted = emit({
      "users.model.ts": `import { Validation } from "@aponiajs/common";
import { t } from "elysia";

const createUserSchema = t.Object({ name: t.String() });
const updateUserSchema = t.Partial(createUserSchema);

@Validation(updateUserSchema)
export class UpdateUser {}
`,
      "shared.model.ts": `import { Validation } from "@aponiajs/common";
import { t } from "elysia";

@Validation(t.Object({ id: t.String() }))
export class UpdateUser {}
`,
      "users.controller.ts": `import { Body, Controller, Patch } from "@aponiajs/common";
import { UpdateUser } from "./users.model.ts";

@Controller("users")
export class UsersController {
  @Patch("/", { body: UpdateUser })
  update(@Body() body: UpdateUser): string {
    return JSON.stringify(body);
  }
}
`,
      "users.module.ts": `import { Module } from "@aponiajs/common";
import { UsersController } from "./users.controller.ts";

@Module({ controllers: [UsersController] })
export class UsersModule {}
`,
    });

    // Two classes are named `UpdateUser`, so the emitter cannot tell which one
    // the slot meant and copies the class the controller imported — the one
    // thing it must not do is substitute the other file's validator.
    expect(emitted.declined).toEqual([]);
    expect(emitted.source).toContain('import { UpdateUser } from "./users.model.ts";');
    expect(emitted.source).not.toContain("t.Partial");

    const single = emit({
      "users.model.ts": `import { Validation } from "@aponiajs/common";
import { t } from "elysia";

const createUserSchema = t.Object({ name: t.String() });
const updateUserSchema = t.Partial(createUserSchema);

@Validation(updateUserSchema)
export class UpdateUser {}
`,
      "users.controller.ts": `import { Body, Controller, Patch } from "@aponiajs/common";
import { UpdateUser } from "./users.model.ts";

@Controller("users")
export class UsersController {
  @Patch("/", { body: UpdateUser })
  update(@Body() body: UpdateUser): string {
    return JSON.stringify(body);
  }
}
`,
      "users.module.ts": `import { Module } from "@aponiajs/common";
import { UsersController } from "./users.controller.ts";

@Module({ controllers: [UsersController] })
export class UsersModule {}
`,
    });

    expect(single.declined).toEqual([]);
    expect(single.source).toContain("schema: { body: t.Partial(t.Object({ name: t.String() })) },");
  });

  test("declines a route whose model validator cannot be reproduced", () => {
    const emitted = emit({
      "users.model.ts": `import { Validation } from "@aponiajs/common";
import { t } from "elysia";

let reassigned = t.Object({ name: t.String() });

@Validation(reassigned)
export class ReassignedUser {}
`,
      "users.controller.ts": `import { Body, Controller, Patch } from "@aponiajs/common";
import { ReassignedUser } from "./users.model.ts";

@Controller("users")
export class UsersController {
  @Patch("/", { body: ReassignedUser })
  patch(@Body() body: ReassignedUser): string {
    return JSON.stringify(body);
  }
}
`,
      "users.module.ts": `import { Module } from "@aponiajs/common";
import { UsersController } from "./users.controller.ts";

@Module({ controllers: [UsersController] })
export class UsersModule {}
`,
    });

    // A `let` is never folded — it can be reassigned after the decorator ran — so
    // the validator the model declares is a name only that file can read, and the
    // route is declined rather than emitted naming the class.
    const reason =
      'The validator of the model ReassignedUser in /project/src/users.model.ts reads "reassigned", ' +
      "which is not an import or an export of the file it was written in, so a generated module cannot name it.";
    expect(emitted.source).toBeUndefined();
    expect(emitted.declined).toEqual([
      {
        kind: "route",
        module: "UsersModule",
        controller: "UsersController",
        method: "patch",
        reason,
      },
      { kind: "module", module: "UsersModule", reason },
    ]);
  });

  test("declines a route whose model reads its constants in a cycle", () => {
    const emitted = emit({
      "users.model.ts": `import { Validation } from "@aponiajs/common";
import { t } from "elysia";

const first = t.Object({ name: second });
const second = t.Object({ name: first });

@Validation(first)
export class CyclicUser {}
`,
      "users.controller.ts": `import { Body, Controller, Post } from "@aponiajs/common";
import { CyclicUser } from "./users.model.ts";

@Controller("users")
export class UsersController {
  @Post("/", { body: CyclicUser })
  create(@Body() body: CyclicUser): string {
    return JSON.stringify(body);
  }
}
`,
      "users.module.ts": `import { Module } from "@aponiajs/common";
import { UsersController } from "./users.controller.ts";

@Module({ controllers: [UsersController] })
export class UsersModule {}
`,
    });

    expect(emitted.source).toBeUndefined();
    // A constant that reads itself has no value to fold, so the analysis reports
    // the cycle rather than following it.
    const reason =
      'The validator of the model CyclicUser in /project/src/users.model.ts reads "first" through ' +
      "a cycle of constants, which cannot be resolved.";
    expect(emitted.declined).toEqual([
      {
        kind: "route",
        module: "UsersModule",
        controller: "UsersController",
        method: "create",
        reason,
      },
      { kind: "module", module: "UsersModule", reason },
    ]);
  });

  test("declares a gateway provider through defineWebSocketGateway", () => {
    const emitted = emit({
      "events.gateway.ts": `import { ConnectedSocket, MessageBody, SubscribeMessage, WebSocketGateway, WebSocketServer } from "@aponiajs/common";
import type { Elysia } from "elysia";

@WebSocketGateway("/events")
export class EventsGateway {
  @WebSocketServer()
  server!: Elysia;

  @SubscribeMessage("events.echo")
  echo(@MessageBody("value") value: string, @ConnectedSocket() socket: unknown): unknown {
    return { value, socket };
  }

  @SubscribeMessage("events.silent")
  silent(): undefined {
    return undefined;
  }
}
`,
      "events.module.ts": `import { Module } from "@aponiajs/common";
import { EventsGateway } from "./events.gateway.ts";

@Module({ providers: [EventsGateway] })
export class EventsModule {}
`,
    });

    expect(emitted.declined).toEqual([]);
    expect(emitted.source).toContain(
      'import { defineWebSocketGateway } from "@aponiajs/platform-elysia";',
    );
    expect(emitted.source).toContain(`defineWebSocketGateway(EventsGateway, {
      path: "/events",
      inject: [],
      handlers: [
        {
          event: "events.echo",
          propertyKey: "echo",
          parameters: [
            { index: 0, kind: "message-body", property: "value" },
            { index: 1, kind: "connected-socket", property: undefined },
          ],
        },
        {
          event: "events.silent",
          propertyKey: "silent",
        },
      ],
      serverProperties: ["server"],
    }),`);
  });

  test("declares a gateway that is also @Injectable() once, with its dependencies", () => {
    const emitted = emit({
      "events.gateway.ts": `import { Injectable, SubscribeMessage, WebSocketGateway } from "@aponiajs/common";
import { AuditService } from "./audit.service.ts";

@Injectable()
@WebSocketGateway("events")
export class EventsGateway {
  constructor(private readonly auditService: AuditService) {}

  @SubscribeMessage("events.echo")
  echo(): string {
    return this.auditService.read();
  }
}
`,
      "audit.service.ts": `import { Injectable } from "@aponiajs/common";

@Injectable()
export class AuditService {
  read(): string {
    return "audited";
  }
}
`,
      "events.module.ts": `import { Module } from "@aponiajs/common";
import { AuditService } from "./audit.service.ts";
import { EventsGateway } from "./events.gateway.ts";

@Module({ providers: [EventsGateway, AuditService] })
export class EventsModule {}
`,
    });

    expect(emitted.declined).toEqual([]);
    expect(emitted.source).toContain(
      'defineWebSocketGateway(EventsGateway, {\n      path: "events",\n      inject: [AuditService],',
    );
  });

  test("declines a module whose gateway declares a handler the analysis cannot read", () => {
    const emitted = emit({
      "events.gateway.ts": `import { MessageBody, SubscribeMessage, WebSocketGateway } from "@aponiajs/common";

const event = "events.echo";

@WebSocketGateway()
export class EventsGateway {
  @SubscribeMessage(event)
  echo(@MessageBody() data: unknown): unknown {
    return data;
  }
}
`,
      "events.module.ts": `import { Module } from "@aponiajs/common";
import { EventsGateway } from "./events.gateway.ts";

@Module({ providers: [EventsGateway] })
export class EventsModule {}
`,
    });

    // The event is a module-private binding, so no generated plan can state it —
    // and a plan that dropped the handler would answer for a message the
    // application used to handle.
    expect(emitted.source).toBeUndefined();
    expect(emitted.declined).toEqual([
      {
        kind: "module",
        module: "EventsModule",
        reason:
          "@SubscribeMessage on the method echo in /project/src/events.gateway.ts declares an event " +
          "this analysis cannot read statically.",
      },
    ]);
  });
});
